protected/controllers/CupoController.php
<?php

class CupoController extends GxController {

	public function filters() {
			return array(
					'rights', 
					);
		}

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Cupo'),
		));
	}

	public function actionCreate() {
		$model = new Cupo;

		$this->performAjaxValidation($model, 'cupo-form');

		if (isset($_POST['Cupo'])) {
			$model->setAttributes($_POST['Cupo']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Cupo');

		$this->performAjaxValidation($model, 'cupo-form');

		if (isset($_POST['Cupo'])) {
			$model->setAttributes($_POST['Cupo']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Cupo')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Cupo');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Cupo('search');
		$model->unsetAttributes();

		if (isset($_GET['Cupo']))
			$model->setAttributes($_GET['Cupo']);

		$this->render('admin', array(
			'model' => $model,
		));
	}
        
        public function actionEliminarTodos(){
            $model = new Cupo;
            Cupo::model()->deleteAll();
            $this->redirect(array('admin'));
        }

}

protected/controllers/EstadoController.php
<?php

class EstadoController extends GxController {

	public function filters() {
			return array(
					'rights', 
					);
		}

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Estado'),
		));
	}

	public function actionCreate() {
		$model = new Estado;

		$this->performAjaxValidation($model, 'estado-form');

		if (isset($_POST['Estado'])) {
			$model->setAttributes($_POST['Estado']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}
        
        public function actionCrear() {
		$model = new Estado;
                $status_model=Estado::model()->ultimo()->find();
		if($status_model->estado=='CERRADO')
			$model->estado='ACTIVO';
		if($status_model->estado=='ACTIVO')
			$model->estado='CERRADO';
		
                $session=Yii::app()->getSession();
		$id_user=$session['_id'];
		$model->user_id=$id_user;
                
		$model->fechaInicio=date("Y-m-d H:i:s",time());
                $status_model->fechaTermino= $model->fechaInicio;
                $status_model->save(false);
		$this->performAjaxValidation($model, 'estado-form');
                if (isset($_POST['Estado'])) {
			$model->setAttributes($_POST['Estado']);
                if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('admin', 'id' => $model->id));
                }
                }

		$this->render('crear', array( 'model' => $model));

		
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Estado');

		$this->performAjaxValidation($model, 'estado-form');

		if (isset($_POST['Estado'])) {
			$model->setAttributes($_POST['Estado']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Estado')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Estado');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
            
                $status_model=Estado::model()->ultimo()->find();
		Yii::app()->user->setFlash('notice', "SISTEMA :  ".$status_model->estado." ");
                
		$model = new Estado('search');
		$model->unsetAttributes();

		if (isset($_GET['Estado']))
			$model->setAttributes($_GET['Estado']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

protected/controllers/LocalController.php
<?php

class LocalController extends GxController {

	public function filters() {
			return array(
					'rights', 
					);
		}

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Local'),
		));
	}

	public function actionCreate() {
		$model = new Local;

		$this->performAjaxValidation($model, 'local-form');

		if (isset($_POST['Local'])) {
			$model->setAttributes($_POST['Local']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Local');

		$this->performAjaxValidation($model, 'local-form');

		if (isset($_POST['Local'])) {
			$model->setAttributes($_POST['Local']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Local')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Local');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Local('search');
		$model->unsetAttributes();

		if (isset($_GET['Local']))
			$model->setAttributes($_GET['Local']);

		$this->render('admin', array(
			'model' => $model,
		));
	}
	
	public function actionVerLocalesCliente() {
		$model = new Local('search');
		$model->unsetAttributes();
		$dataProvider=$model->cargarLocalesCliente();
		
		$this->render('verLocalesCliente',array('dataProvider'=>$dataProvider,'model'=>$model));
	}
	
	public function actionVerLocalCliente($id) {
		
		$model = $this->loadModel($id, 'Local');
                $recargas_local = new Recarga;
                
		$dataProvider=$recargas_local->cargarRecargasLocal($id);
		$this->render('verLocalCliente',array('dataProvider'=>$dataProvider,'model'=>$model));
	}
	
}//finfin

protected/controllers/UserController.php
<?php

class UserController extends GxController {

    public function filters() {
            return array(
                            'rights', 
                            );
    }


	public function actionIngresar($id){
	
	
	
	
	$local_model = $this->loadModel($id, 'Local');
	$estado=$local_model->user->estado;
	
	if (Yii::app()->request->isAjaxRequest)
        {
			if($estado!="ACTIVO"){
				echo CJSON::encode(array('status'=>'failure', 'content'=>'CLIENTE INACTIVO'));
				exit;               
			}
        }
	
	if (Yii::app()->request->isAjaxRequest)
        {
		if ($local_model->id!= NULL){
			$session=Yii::app()->getSession();
			$session['_local']=$local_model->id;
				if ($session['_local']!= NULL) {
				
					if (Yii::app()->request->isAjaxRequest){
							echo CJSON::encode(array(
							'status'=>'success', 
							'content'=>$this->createUrl('recarga/create'),
							));
						exit;               
					}
				}
		}
	}
	
}
	
	public function actionElegir()
	{
		
		$session=Yii::app()->getSession();
		$id_user=$session['_id'];
		$model_user = $this->loadModel($id_user, 'User');
		$id_user=$model_user->user->id;
		
		$locales= new CArrayDataProvider($model_user->user->locales,array());
		
		Yii::app()->user->setFlash('info', 'Porfavor seleccione el <strong>LOCAL</strong> en el cual se encuentra.');
		$this->render('local',array('model'=>$locales,'user_id'=>$id_user));
		
	}

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'User'),
		));
	}

	public function actionCreate() {
		$model = new User;

		$this->performAjaxValidation($model, 'user-form');

		if (isset($_POST['User'])){
			$model->setAttributes($_POST['User']);
			$model->password=$model->hashPassword($model->password,$model->salt);

			if ($model->save()) {
                            Rights::assign($model->tipo, $model->id);
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionEditar($id) {
		$model = $this->loadModel($id, 'User');
                $model->password=NULL;
		$this->performAjaxValidation($model, 'user-form');

		if (isset($_POST['User'])) {
			$model->setAttributes($_POST['User']);
			$model->password=$model->hashPassword($model->password,'28b206548469ce62182048fd9cf91760');

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('editar', array(
				'model' => $model,
				));
	}
        
        public function actionUpdate($id) {
		$model = $this->loadModel($id, 'User');

		$this->performAjaxValidation($model, 'user-form');

		if (isset($_POST['User'])) {
			$model->setAttributes($_POST['User']);
			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'User')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('User');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new User('search');
		$model->unsetAttributes();

		if (isset($_GET['User']))
			$model->setAttributes($_GET['User']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

}

protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="container">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="container">
	<div class="span-19">
		<div id="content">
			<?php echo $content; ?>
		</div><!-- content -->
	</div>
	<div class="span-5 last">
		<div id="sidebar">
		<?php
			$this->widget('bootstrap.widgets.TbMenu',array(
			'type'=>'pills',
			'stacked'=> false,
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),	
		
		));
		
		?>
		</div><!-- sidebar -->
	</div>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40741810-2', 'recargaschile.cl');
  ga('send', 'pageview');

</script>
<div class="container" id="page">

	<div id="header">
		<div id="logo"></div>
	</div><!-- header -->
<br>
	<div id="mainmenu">
		
		<?php 
		$session=Yii::app()->getSession();
		$_tipo=($session['_tipo']);
		$_local=($session['_local']);
		?>
		
			
		<?php	
		if($_tipo== NULL):			
	
		$this->widget('bootstrap.widgets.TbNavbar', array(
		    //'type'=>'inverse', // null or 'inverse'
		    'brand'=>'RCH 2.0',
		    'brandUrl'=>array('/site/index'),
		    //'collapse'=>true, // requires bootstrap-responsive.css
		    'items'=>array(
		        array(
		            'class'=>'bootstrap.widgets.TbMenu',
		            'items'=>array(
		                array('label'=>'Home', 'url'=>array('/site/index'),),
		                array('label'=>'Login', 'url'=>array('/site/login'),),
						
		                
		            ),
		        ),
		  	)
		)); 
		
		endif; ?>
		
		<?php	
		if($_tipo== "ADMIN"):
			
		$this->widget('bootstrap.widgets.TbNavbar', array(
		    'type'=>'inverse', // null or 'inverse'
		    'brand'=>'RCH 2.0',
		    'brandUrl'=>array('/site/index'),
		    'collapse'=>true, // requires bootstrap-responsive.css
		    'items'=>array(
		        array(
		            'class'=>'bootstrap.widgets.TbMenu',
		            'items'=>array(
		                array('label'=>'Roles', 'url'=>array('/rights')),
						array('label'=>'Usuarios', 'url'=>array('/user/admin')),
						array('label'=>'Locales', 'url'=>array('/local/admin')),
						//array('label'=>'Recargas', 'url'=>array('/reporteGeneral/admin')),
                                                array('label' => 'Reportes', 'url' => '#', 'items' => array(
                                                    array('label' => 'Recarga', 'url' => array('/reporteGeneral/admin')),
                                                    array('label' => 'Cliente', 'url' => array('/reporteGeneral/reporteCliente')),
                                                    array('label' => 'Cliente Simple', 'url' => array('/reporteGeneral/reporteClienteSimple')),
                                                    array('label' => 'Operador', 'url' => array('/reporteGeneral/reporteOperador')),
                                                )),
						array('label'=>'Cupo', 'url'=>array('/cupo/admin')),
						array('label'=>'No Prepagos', 'url'=>array('/noprepago/admin')),
						array('label'=>'Atenciones', 'url'=>array('/atencion/admin')),
						array('label'=>'Productos', 'url'=>array('/producto/verTodos')),
						array('label'=>'Pedidos', 'url'=>array('/pedido/verTodos')),
						array('label'=>'Publicidades', 'url'=>array('/publicidad/verTodos')),
						array('label' => 'Mensaje', 'url' => '#', 'items' => array(
                                                    array('label' => 'Crear Nuevo Mensaje', 'url' => array('/mensaje/crearNuevo')),
                                                    array('label' => 'Bandeja de entrada', 'url' => array('/mensaje/todos')),
                                                    
                                                )),
						array('label'=>'Estado', 'url'=>array('/estado/admin')),
						array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
						array('label'=>'Logout ['.$session['_username'].']', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
		                
		            ),
		        ),
		  	)
		)); 
		
		endif; ?>
		
		<?php	
		if($_tipo== "EMPLEADO" and $_local):
				
		$this->widget('bootstrap.widgets.TbNavbar', array(
		    'type'=>'inverse', // null or 'inverse'
		    'brand'=>'RCH 2.0',
		    'brandUrl'=>array('/site/index'),
		    'collapse'=>true, // requires bootstrap-responsive.css
		    'items'=>array(
		        array(
		            'class'=>'bootstrap.widgets.TbMenu',
		            'items'=>array(
		                array('label'=>'Home', 'url'=>array('/site/index')),
						array('label'=>'Recargar', 'url'=>array('/recarga/create')),
						array('label'=>'En Proceso', 'url'=>array('/recarga/verPendientesEmpleado')),
						array('label'=>'Recargas Listas', 'url'=>array('/recarga/verListasEmpleado')),
						array('label'=>'Chat','icon'=>'envelope', 'url'=>array('/mensaje/crear')),
                                                array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
						array('label'=>'Logout ('.$session['_username'].')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
		                
		            ),
		        ),
		  	)
		)); 
		
		endif; ?>
		
		<?php	
		if($_tipo== "EMPLEADO" and !$_local):
				
		$this->widget('bootstrap.widgets.TbNavbar', array(
		    'type'=>'inverse', // null or 'inverse'
		    'brand'=>'RCH 2.0',
		    'brandUrl'=>array('/site/index'),
		    'collapse'=>true, // requires bootstrap-responsive.css
		    'items'=>array(
		        array(
		            'class'=>'bootstrap.widgets.TbMenu',
		            'items'=>array(
		                array('label'=>'Home', 'url'=>array('/site/index')),
		                array('label'=>'Eligir Local', 'url'=>array('/user/elegir')),
						array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
						array('label'=>'Logout ('.$session['_username'].')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
		                
		            ),
		        ),
		  	)
		)); 
		
		endif; ?>
		
		
		<?php	
		if($_tipo== "OPERADOR"):
			
		$this->widget('bootstrap.widgets.TbNavbar', array(
		    'type'=>'inverse', // null or 'inverse'
		    'brand'=>'RCH 2.0',
		    'brandUrl'=>array('/site/index'),
		    'collapse'=>true, // requires bootstrap-responsive.css
		    'items'=>array(
		        array(
		            'class'=>'bootstrap.widgets.TbMenu',
		            'items'=>array(
		                array('label'=>'Home', 'url'=>array('/site/index')),
						//array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
						//array('label'=>'Contact', 'url'=>array('/site/contact')),
						array('label'=>'Atender Recargas', 'url'=>array('/recarga/verPendientesOperador')),
						array('label'=>'Recargas Listas', 'url'=>array('/atencion/verListasOperador')),
						array('label'=>'Chat','icon'=>'envelope', 'url'=>array('/mensaje/crear')),
						array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
						array('label'=>'Logout ('.$session['_username'].')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
					),
		                
		        ),
		    ),
		)
		); 
		
		endif; ?>
		
		<?php	
		if($_tipo== "CLIENTE"):
			
		$this->widget('bootstrap.widgets.TbNavbar', array(
		    'type'=>'inverse', // null or 'inverse'
		    'brand'=>'RCH 2.0',
		    'brandUrl'=>array('/site/index'),
		    'collapse'=>true, // requires bootstrap-responsive.css
		    'items'=>array(
		        array(
		            'class'=>'bootstrap.widgets.TbMenu',
		            'items'=>array(
		                array('label'=>'Home', 'url'=>array('/site/index')),
						//array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
						//array('label'=>'Contact', 'url'=>array('/site/contact')),
						array('label'=>'Locales', 'url'=>array('/local/verLocalesCliente')),
						array('label'=>'Chat','icon'=>'envelope', 'url'=>array('/mensaje/crear')),
						//array('label'=>'Atenciones', 'url'=>array('/atencion/admin')),
                                                //array('label'=>'Historico Recargas', 'url'=>array('/recarga/verHistorico', 'id'=>$_local)),
						array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
						array('label'=>'Logout ('.$session['_username'].')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
					),
		                
		        ),
		    ),
		)
		); 
		
		endif; ?>
		
			
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
	<?php $this->widget('bootstrap.widgets.TbBreadcrumbs', array(
    'links'=>$this->breadcrumbs,
)); ?>
		<?php /*$this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); */?><!-- breadcrumbs -->
	<?php endif?>

	<?php echo $content; ?>

	
	<?php /* <div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer --> */ ?>

</div><!-- page -->

</body>
</html>